language: java

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

notifications:
  email: false
  irc:
    - "irc.dilley.me#sysadmininkudzu"
    - "chat.freenode.net#linulator"
    - "irc.oftc.net#linulator"
